### ISSUE TITLE
Cannot process value type hex(9)

### ISSUE THREAD

**Issue by Lavshyak** [cklutz/RegFile#3]
```
using RegFile;

using var reader = new RegFileReader("C:\\CodeProjects\\NET\\RegCSVToReg\\FullReester.reg");
var commands = reader.Read(); //exception

return 0;
```

```
System.IO.IOException: Cannot process value type hex(9) in C:\CodeProjects\NET\RegCSVToReg\FullReester.reg, line 4508
   at RegFile.RegFileExtensions.ParseException(SourceLocation location, String msg) in C:\CodeProjects\NET\RegCSVToReg\RegFile\RegFile\RegFileExtensions.cs:line 85
   at RegFile.RegFileReader.Read() in C:\CodeProjects\NET\RegCSVToReg\RegFile\RegFile\RegFileReader.cs:line 194
```

part of .reg. line 4508 is "Configuration Data"=hex(9):ff,ff,ff,ff,ff,ff,ff,ff,00,00,00,00,02,00,00,00,05,\
```
[HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION]

[HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System]
"Component Information"=hex:00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00
"Identifier"="AT/AT COMPATIBLE"
"Configuration Data"=hex(9):ff,ff,ff,ff,ff,ff,ff,ff,00,00,00,00,02,00,00,00,05,\
  00,00,00,0c,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,ff,ff,ff,ff,\
  00,00,ff,ff,01,00,05,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,\
  00
"SystemBiosVersion"=hex(7):49,00,4e,00,54,00,45,00,4c,00,20,00,20,00,2d,00,20,\
  00,36,00,30,00,34,00,30,00,30,00,30,00,30,00,00,00,56,00,4d,00,57,00,32,00,\
  30,00,31,00,2e,00,30,00,30,00,56,00,2e,00,32,00,31,00,38,00,30,00,35,00,34,\
  00,33,00,30,00,2e,00,42,00,36,00,34,00,2e,00,32,00,33,00,30,00,35,00,32,00,\
  32,00,31,00,38,00,33,00,30,00,00,00,56,00,4d,00,77,00,61,00,72,00,65,00,2c,\
  00,20,00,49,00,6e,00,63,00,2e,00,20,00,2d,00,20,00,31,00,30,00,30,00,30,00,\
  30,00,00,00,00,00
"BootArchitecture"=dword:00000003
"PreferredProfile"=dword:00000000
"Capabilities"=dword:00004421

[HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System\CentralProcessor]
```

**Comment by Lavshyak** [comment]
possible random fix:
RegFileExtensions.cs:197
```
                case "hex(8)":
                    return new RegValueInfo(RegistryValueKind.Binary, RegistryValueFormat.HexValuesBE);
                case "hex(9)":
                    return new RegValueInfo(RegistryValueKind.Binary, RegistryValueFormat.HexValuesBE);
```
