### ISSUE TITLE
Missing ':' in value in

### ISSUE THREAD

**Issue by Lavshyak** [cklutz/RegFile#4]
```
System.IO.IOException: Missing ':' in value in C:\CodeProjects\NET\RegCSVToReg\FullReester.reg, line 674059
   at RegFile.RegFileExtensions.ParseException(SourceLocation location, String msg) in C:\CodeProjects\NET\RegCSVToReg\RegFile\RegFile\RegFileExtensions.cs:line 85
   at RegFile.RegFileReader.Read() in C:\CodeProjects\NET\RegCSVToReg\RegFile\RegFile\RegFileReader.cs:line 187
```

line 674059 is "Root\\CIMV2:__Win32Provider.Name=\"CIMWin32\""="0"
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Wbem\CIMOM\CompatibleHostProviders]

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Wbem\CIMOM\SecuredHostProviders]
"Root\\CIMV2:__Win32Provider.Name=\"CIMWin32\""="0"
```

![изображение](https://github.com/user-attachments/assets/05ae1f83-83a3-4fea-9846-448cd87c4712)

**Comment by Lavshyak** [comment]
ну тут хз

**Comment by Lavshyak** [comment]
It seems that code ignores \ before "
